linter:
  rules:
    - camel_case_types
    - empty_constructor_bodies
    - empty_statements
    - hash_and_equals
    - implementation_imports
    - leading_newlines_in_multiline_strings
    - library_names
    - library_prefixes
    - no_adjacent_strings_in_list
    - null_closures
    - prefer_final_fields
    - prefer_generic_function_type_aliases
    - prefer_void_to_null
    - recursive_getters
    - slash_for_doc_comments
    - sort_pub_dependencies
    - type_init_formals
    - unnecessary_brace_in_string_interps
    - unnecessary_getters_setters
